name: PR Validation

on:
  pull_request:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: .
      - name: Install dependencies
        run: npm install
      - name: Lint HTML
        run: npx htmlhint "**/*.html"
      - name: Lint CSS
        run: npx stylelint "**/*.css"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: .
      - name: Install dependencies
        run: npm install
      - name: Build Project
        run: npx parcel build src/*.html --dist-dir build
