name: PR Validation

on:
  pull_request:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        working-directory: .  # 👈 correct directory
      - name: Lint HTML
        run: npx htmlhint "**/*.html"
        working-directory: .
      - name: Lint CSS
        run: npx stylelint "**/*.css"
        working-directory: .

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        working-directory: .
      - name: Build Project
        run: npx parcel build src/*.html --dist-dir build
        working-directory: .
